config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show index edit update]

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, concerns: :likeable, shallow: true do
    resources :comments, concerns: :likeable
  end

  resources :notifications, only: %i[index]

  resources :friendships, only: %i[index create update destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  # content:string

  belongs_to :author, class_name: "User"
  belongs_to :parent, class_name: "Post"

  has_many :likes, as: :likeable, foreign_key: "likeable_id", dependent: :destroy

  scope :ordered, -> { order(created_at: :desc) }

  def liked?(user)
    likes.exists?(author: user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.includes(:author)
  end

  def show
    @comment = Comment.find(params[:id])
    @post = @comment.parent
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      respond_to do |format|
        format.html { redirect_to @post, status: :created }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to @comment, status: :see_other }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.parent
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @post }
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_button_text(post)
    "Comments (#{post.comments.count})"
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment, class: "box" do %>
  <div data-controller="navbar" data-navbar-change-class="is-active">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img alt="<%= comment.author.name %>" src="<%= avatar_url(user: comment.author, size: 64) %>">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>
              <%= comment.author.name %>
            </strong> <small> <%= distance_of_time_in_words(comment.created_at, Time.now) %> </small>
            <br>
            <%= comment.content %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <span class="level-item is-small">
              <%= render select_like_form(comment), likeable: comment %>
            </span>
            <a class="level-item">
              <span class="is-small">comment</span>
            </a>
          </div>
        </nav>
      </div>
      <div class="media-right">
        <div class="dropdown is-right" data-navbar-target="dropdown">
          <div class="dropdown-trigger">
            <button id="comment_<%= comment.id %>_dropdown_button" class="button" data-action="navbar#toggleDropdown">:</button>
          </div>
          <div class="dropdown-menu">
            <div class="dropdown-content">
              <%= link_to "Permalink", comment_path(comment), class: "dropdown-item",
               data: { turbo: false } %>
              <% if comment.author == current_user %>
                <%= link_to "Edit", edit_comment_path(comment), class: "dropdown-item" %>
                <hr class="dropdown-divider">
                <%= link_to "Delete", comment_path(comment), class: "dropdown-item",
                 data: { turbo_method: :delete, turbo_confirm: "Really delete this comment?" } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag "post_#{post.id}_comment_form", class: "container" do %>
  <%= form_with model: comment, url: post_comments_path(post) , class: "content",
   data: { controller: "submission", action: "turbo:submit-end->submission#clear input->submission#toggleButton" } do |comment_form| %>
    <%= comment_form.text_area :content, id: "post_#{post.id}_comment_field", class: "textarea has-fixed-size", placeholder: "Write a comment...", data: { submission_target: "textarea" } %>
    <%= comment_form.submit "Add Comment", class: "button is-link", disabled: false, data: { submission_target: "button" } %>
  <% end %>
<% end %>

app/views/comments/_update_form.html.erb
<%= turbo_frame_tag "comment_#{comment.id}_update_form", class: "container" do %>
  <%= form_with model: comment, class: "content",
   data: { controller: "submission", action: "turbo:submit-end->submission#clear input->submission#toggleButton" } do |comment_form| %>
    <%= comment_form.text_area :content, id: "comment_#{comment.id}_update_field", class: "textarea has-fixed-size", placeholder: "Write a comment...", data: { submission_target: "textarea" } %>
    <%= comment_form.submit "Update Comment", class: "button is-link", disabled: false, data: { submission_target: "button" } %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "post_#{@post.id}_comments" do %>
  <%= render @comment %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "update_form", comment: @comment %>
<% end %>

app/views/comments/index.html.erb
<%= turbo_frame_tag "post_#{@post.id}_comments" do %>
  <%= render @comments %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "post_#{@post.id}_comment_form" do %>
  <%= render 'comments/form', post: @post, comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @post, class: "box" do %>
  <div data-controller="navbar" data-navbar-change-class="is-active">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img alt="<%= @post.author.name %>" src="<%= avatar_url(user: @post.author, size: 64) %>">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>
              <%= @post.author.name %>
            </strong> <small> <%= distance_of_time_in_words(@post.created_at, Time.now) %> </small>
            <br>
            <%= @post.content %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <span class="level-item is-small">
              <%= render select_like_form(@post), likeable: @post %>
            </span>
            <%= button_to comments_button_text(@post), post_comments_path(@post.id), class: "button level-item" %>
          </div>
        </nav>
      </div>
      <div class="media-right">
        <div class="dropdown is-right" data-navbar-target="dropdown">
          <div class="dropdown-trigger">
            <button id="post_<%= @post.id %>_dropdown_button" class="button" data-action="navbar#toggleDropdown">:</button>
          </div>
          <div class="dropdown-menu">
            <div class="dropdown-content">
              <%= link_to "Permalink", post_path(@post), class: "dropdown-item",
               data: { turbo: false } %>
              <% if @post.author == current_user %>
                <%= link_to "Edit", edit_post_path(@post), class: "dropdown-item" %>
                <hr class="dropdown-divider">
                <%= link_to "Delete", post_path(@post), class: "dropdown-item",
                 data: { turbo_method: :delete, turbo_confirm: "Really delete this post?" } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </article>
    <% if @post.comments.count > 1 %>
      <div id="comment_omission_notification" class="notification" style="margin-top: 24px">
        <span>
          <%= pluralize(@post.comments.count - 1, "comment") %> hidden.
          <%= link_to "Show all",
            post_path(@post),
           data: { turbo: false } %>
        </span>
      </div>
    <% end %>
    <%= turbo_frame_tag "post_#{@post.id}_comments", class: "container" do %>
      <%= render "comment", comment: @comment %>
    <% end %>
    <%= turbo_frame_tag "post_#{@post.id}_comment_form", src: new_post_comment_path(@post.id), class: "container" %>
  </div>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace @comment do %>
  <%= render @comment %>
<% end %>