config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show index edit update]

  concern :likeable do
    resources :likes, only: %i[create destroy]
  end

  resources :posts, concerns: :likeable, shallow: true do
    resources :comments, concerns: :likeable
  end

  resources :notifications, only: %i[index]

  resources :friendships, only: %i[index create update destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  # content:string

  belongs_to :author, class_name: "User"

  has_many :comments, foreign_key: "parent_id", dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  scope :ordered, -> { order(created_at: :desc) }

  def self.relevant(current_user)
    where(author: current_user.friends).or(where(author: current_user))
  end

  def liked?(user)
    likes.exists?(author: user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @friends = current_user.friends
    @posts = Post.relevant(current_user).ordered.includes(:author)
    @post = current_user.posts.build
  end

  def show
    @post = Post.find_by(id: params[:id])

    if @post.present?
      render :show
    else
      render file: "#{Rails.root}/public/404.html", layout: true, status: :not_found
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @new_post = current_user.posts.build

    if @post.save
      respond_to do |format|
        format.html { redirect_to @post, status: :see_other }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      respond_to do |format|
        format.html { redirect_to @post, status: :see_other }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.turbo_stream
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= turbo_frame_tag "new_post" do %>
  <%= form_with model: @post,
     data: { controller: "submission", action: "turbo:submit-end->submission#clear input->submission#toggleButton" } do |post_form| %>
    <%= post_form.text_area :content,
       class: "textarea has-fixed-size",
       placeholder: "Share what you're thinking",
       data: { submission_target: "textarea" } %>
    <%= post_form.submit class: "button is-primary", disabled: false, data: { submission_target: "button" } %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post, class: "box" do %>
  <div data-controller="navbar" data-navbar-change-class="is-active">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img alt="<%= post.author.name %>" src="<%= avatar_url(user: post.author, size: 64) %>">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>
              <%= post.author.name %>
            </strong> <small> <%= distance_of_time_in_words(post.created_at, Time.now) %> </small>
            <br>
            <%= post.content %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <span class="level-item is-small">
              <%= render select_like_form(post), likeable: post %>
            </span>
            <%= button_to comments_button_text(post), post_comments_path(post.id), class: "button level-item" %>
          </div>
        </nav>
      </div>
      <div class="media-right">
        <div class="dropdown is-right" data-navbar-target="dropdown">
          <div class="dropdown-trigger">
            <button id="post_<%= post.id %>_dropdown_button" class="button" data-action="navbar#toggleDropdown">:</button>
          </div>
          <div class="dropdown-menu">
            <div class="dropdown-content">
              <%= link_to "Permalink", post_path(post), class: "dropdown-item",
               data: { turbo: false } %>
              <% if post.author == current_user %>
                <%= link_to "Edit", edit_post_path(post), class: "dropdown-item" %>
                <hr class="dropdown-divider">
                <%= link_to "Delete", post_path(post), class: "dropdown-item",
                 data: { turbo_method: :delete, turbo_confirm: "Really delete this post?" } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </article>
    <%= turbo_frame_tag "post_#{post.id}_comments", src: post_comments_path(post.id), class: "container" %>
    <%= turbo_frame_tag "post_#{post.id}_comment_form", src: new_post_comment_path(post.id), class: "container" %>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render @post, comments: @post.comments %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag @post do %>
  <%= render "form", post: @post %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <%= turbo_frame_tag "new_post", src: new_post_path %>
</div>

<div class="container is-max-desktop">
  <%= turbo_frame_tag "posts" do %>
    <% @posts.each do |post| %>
      <%= render post, comments: post.comments %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "new_post" do %>
  <%= form_with model: @post,
    data: { controller: "submission", action: "turbo:submit-end->submission#clear" }  do |post_form| %>
    <%= post_form.text_area :content,
     class: "textarea has-fixed-size",
     placeholder: "Share what you're thinking",
     data: { submission_target: "textarea" } %>
    <%= post_form.submit "Create Post", class: "button is-primary" %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<%= render @post, comments: @comments %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.replace @post do %>
  <%= render @post, comments: @post.comments %>
<% end %>